{{- if .Values.rbac -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "serviceAccountName" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
{{- with .Values.rbac.rules }}
rules:
  {{- toYaml . | nindent 4 }}
      {{- end }}
{{- end -}}
