{{- $fullName := include "fullname" . -}}
{{- range .Values.cronJobs}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{.name}}
spec:
  schedule: "{{ .schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            {{- range .containers }}
            - name: "{{ $.Chart.Name }}-cron"
              envFrom:
              - configMapRef:
                    name: "{{ $fullName }}-env"
              {{ if .image }}image: {{ .image }} {{ else }}image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"{{ end }}
              {{ if .command }}command:
                {{- range .command }}
                  - {{ .  }}
                {{- end }}{{end }}
              {{ if .args }}args:
                {{- range .args }}
                  - {{ .  }}
                {{- end }}{{end }}
            {{- end }}
          restartPolicy: {{ .restartPolicy }}
{{- end -}}