{{- range .Values.jobs}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .name  }}
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
        {{- range .containers }}
        - name: "{{ $.Chart.Name }}-job"
          {{ if .image }}image: {{ .image }} {{ else }}image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"{{ end }}
          command: {{ .command}}
        {{- end }}
      restartPolicy: {{ .restartPolicy }}
{{- end -}}