{{- $fullName := include "fullname" . -}}
{{- range .Values.jobs}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .name  }}
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
        {{- range .containers }}
        - name: "{{ $.Chart.Name }}-job"
          envFrom:
          - configMapRef:
              name: "{{ $fullName }}-env"
          {{ if .image }}image: {{ .image }} {{ else }}image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"{{ end }}
          {{ if .command }}command:
           {{- range .command }}
                - {{ .  }}
           {{- end }}{{end }}
          {{ if .args }}args:
           {{- range .args }}
                - {{ .  }}
           {{- end }}{{end }}
        {{- end }}
      restartPolicy: {{ .restartPolicy }}
---
{{- end -}}